"""
可外接使用的模块：
node.
    init_node(node_file_location=r"D:/Files/计算机程序设计/现代程序设计技术/作业数据/newmovies.txt")
    get_item(node_list,key,num=0)
    print_node(node_list,num=0)
stat.
    cal_average_dgree(near_dict)
    cal_dgree_distribution(near_dict)
graph.
    init_graph(node_list,near_dict)
    save_graph(graph_dict,save_location=r"D:/Files/计算机程序设计/现代程序设计技术/作业/第四周作业/graph_dict.txt")
    load_graph(load_location=r"D:/Files/计算机程序设计/现代程序设计技术/作业/第四周作业/graph_dict.txt")
"""